1st Commit
following tutorial : https://www.tutorialspoint.com/spring/spring_hello_world_example.htm

Stuck with error : 

Error: Unable to initialize main class com.tutorialspoint.MainApp
Caused by: java.lang.NoClassDefFoundError: org/springframework/context/ApplicationContext